/**
 * Texture loading and generation.
 *
 * Two kinds live here: real artwork loaded from `public/assets`, and the
 * placeholder combat art generated in code. Keeping both behind one module
 * means swapping a placeholder for a real sprite is a one-line change here and
 * touches nothing in the renderer or the systems.
 */

import {
	Assets,
	Container,
	Graphics,
	Rectangle,
	type Renderer,
	Sprite,
	Texture,
} from "pixi.js";
import { PLAYER_HEIGHT, PLAYER_WIDTH } from "../simulation/Arena";

export const TEX = {
	dude: "dude",
	/** The tumble roll strip — see `rollFrames`. */
	roll: "roll",
	fireball: "fireball",
	platform: "platform",
	sky: "sky",
	spark: "fx_spark",
	shard: "fx_shard",
	ring: "fx_ring",
	arc: "fx_arc",
	blade: "fx_blade",
	guard: "fx_guard",
	/** Staggered by a sword hit. Derived from the dude strip — see `createHitTextures`. */
	disabled: "dude_disabled",
	/** Flat on the floor, after the chain's finisher. */
	downed: "dude_downed",
	/** The black hole's own art — see `createUltimateTextures`. */
	singularity: "fx_singularity",
	horizon: "fx_horizon",
	accretion: "fx_accretion",
	grenade: "fx_grenade",
	halo: "fx_halo",
	/** The soft ellipse every fighter's team-tinted cast shadow is drawn with. */
	shadow: "fx_shadow",
} as const;

/** The `dude` strip, sliced into its nine 32x48 frames. */
export let dudeFrames: Texture[] = [];
/**
 * The roll strip, sliced into sixteen 40x48 frames: 0-7 roll right, 8-15 roll
 * left (the same frames mirrored, so a left roll does not read as a right roll
 * viewed backwards — feet lead the wrong way otherwise).
 */
export let rollFrames: Texture[] = [];

/** One roll cell is wider than the body: a tumbled figure sprawls past it. */
const ROLL_FRAME_W = 40;

const generated = new Map<string, Texture>();

export function tex(key: string): Texture {
	const made = generated.get(key);
	if (made) return made;
	return Assets.get(key) ?? Texture.EMPTY;
}

/**
 * Load the artwork the game ships with.
 *
 * Pixi requires the application to be initialised first, and every load is
 * async — unlike Phaser's preload phase, there is no framework stage that
 * guarantees textures exist before the first frame, so callers must await this.
 */
let manifestRegistered = false;

export async function loadAssets(): Promise<void> {
	const sources: Record<string, string> = {
		[TEX.dude]: "assets/dude.png",
		[TEX.roll]: "assets/roll.png",
		[TEX.fireball]: "assets/fireball.png",
		[TEX.platform]: "assets/platform.png",
		[TEX.sky]: "assets/sky.png",
	};

	// The resolver is global and complains about re-registering an alias. React
	// StrictMode mounts twice in development, so this runs twice on every dev
	// boot; registering once keeps that from filling the console with warnings.
	if (!manifestRegistered) {
		for (const [alias, src] of Object.entries(sources)) {
			Assets.add({ alias, src });
		}
		manifestRegistered = true;
	}
	await Assets.load(Object.keys(sources));

	// The dude sheet is a plain horizontal strip with no atlas JSON, so the
	// frames are cut by hand: 0-3 walk left, 4 face-on, 5-8 walk right.
	const sheet = Assets.get(TEX.dude) as Texture;
	dudeFrames = [];
	for (let i = 0; i < 9; i++) {
		dudeFrames.push(
			new Texture({
				source: sheet.source,
				frame: new Rectangle(i * PLAYER_WIDTH, 0, PLAYER_WIDTH, PLAYER_HEIGHT),
			}),
		);
	}

	// The roll strip follows the same pattern, generated by
	// `scripts/make-roll-art.py` from this same dude strip — see that script
	// for why it is 40px wide rather than 32.
	const rollSheet = Assets.get(TEX.roll) as Texture;
	rollFrames = [];
	for (let i = 0; i < 16; i++) {
		rollFrames.push(
			new Texture({
				source: rollSheet.source,
				frame: new Rectangle(i * ROLL_FRAME_W, 0, ROLL_FRAME_W, PLAYER_HEIGHT),
			}),
		);
	}
}

/**
 * Render a display object to a texture and keep it under `key`.
 *
 * Takes a `Container` rather than a `Graphics` so a generated texture can be a
 * *composition* — the hit poses are the shipped character sprite with shapes
 * drawn over it, which is not something a single `Graphics` can express.
 * `destroy({ children: true })` because the composed ones own their contents.
 */
function bake(renderer: Renderer, key: string, node: Container) {
	generated.set(key, renderer.generateTexture(node));
	node.destroy({ children: true });
}

/**
 * Placeholder combat art, drawn in code.
 *
 * Deliberately crude: flat white primitives that read clearly at speed and are
 * unmistakably temporary. Everything is white so a single tint per effect
 * controls its colour, which is why the real sprites can drop in later without
 * any of the effect code changing.
 */
export function createFxTextures(renderer: Renderer): void {
	if (generated.size > 0) return;

	bake(
		renderer,
		TEX.spark,
		new Graphics().poly([4, 0, 8, 4, 4, 8, 0, 4]).fill(0xffffff),
	);

	bake(renderer, TEX.shard, new Graphics().rect(0, 0, 16, 4).fill(0xffffff));

	bake(
		renderer,
		TEX.ring,
		new Graphics().circle(48, 48, 44).stroke({ width: 5, color: 0xffffff }),
	);

	// A crescent: the swing trail. Drawn facing +x so it can simply be rotated.
	const arc = new Graphics();
	arc.arc(48, 48, 46, -1.0, 1.0, false);
	arc.arc(48, 48, 24, 1.0, -1.0, true);
	arc.closePath();
	arc.fill(0xffffff);
	bake(renderer, TEX.arc, arc);

	// Placeholder sword: blade, guard, grip. To be replaced by real art.
	const blade = new Graphics();
	blade.rect(12, 3, 32, 4).fill(0xdfe7f5);
	blade.rect(8, 0, 3, 10).fill(0x8a94a6);
	blade.rect(0, 3, 8, 4).fill(0x8a94a6);
	bake(renderer, TEX.blade, blade);

	// The guard arc shown while blocking.
	const guard = new Graphics();
	guard.arc(28, 32, 26, Math.PI - 1.1, Math.PI + 1.1, false);
	guard.stroke({ width: 5, color: 0xffffff });
	bake(renderer, TEX.guard, guard);

	// A soft ellipse, white so a team tint decides its colour. Concentric fills
	// rather than one flat shape: a hard-edged oval reads as a decal painted on
	// the floor, and the whole job of this sprite is to read as light being
	// blocked. Drawn wide and shallow because the camera looks slightly down —
	// the same reason the accretion disk is an ellipse.
	const shadow = new Graphics();
	for (let i = 6; i >= 1; i--) {
		shadow.ellipse(32, 16, (30 * i) / 6, (13 * i) / 6).fill({
			color: 0xffffff,
			alpha: 0.13,
		});
	}
	bake(renderer, TEX.shadow, shadow);

	createHitTextures(renderer);
	createUltimateTextures(renderer);
}

/**
 * The black hole's art.
 *
 * The one effect in the game that is **not** flat white waiting for a tint. A
 * singularity is defined by the contrast between a hole that emits nothing and
 * a disk that is far too bright, and a single tinted primitive cannot express
 * both — so the core is baked black-on-transparent, the disk is baked with its
 * own colour ramp, and only the halo stays white so the detonation can tint it.
 *
 * Baked to textures rather than drawn as live `Graphics` because these are
 * scaled and rotated every frame for two seconds: `generateTexture` pays the
 * rasterisation once, and a rotating sprite costs the GPU nothing. See the
 * `pixi-graphics` skill on when to bake.
 */
function createUltimateTextures(renderer: Renderer): void {
	// ---- the core ----
	//
	// Pure black with a tight falloff, and nothing else. Drawn at 128px and scaled
	// down in use, so the edge stays clean at full size.
	//
	// **Deliberately small against the field it belongs to.** The first version
	// faded out over 16px of soft dark, which at a 168px radius washed a third of
	// the arena grey and made the platforms behind it unreadable — a hole should
	// swallow light, not fog the room. The *edge* of the ability is drawn by the
	// horizon ring instead, which is sized from the simulation's own radius.
	const core = new Graphics();
	core.circle(64, 64, 62).fill({ color: 0x000000, alpha: 0.18 });
	core.circle(64, 64, 54).fill({ color: 0x04000c, alpha: 0.72 });
	core.circle(64, 64, 46).fill(0x000000);
	bake(renderer, TEX.singularity, core);

	// ---- the event horizon ----
	//
	// A ring, drawn at exactly the radius the simulation grabs at — see
	// `BlackHoleFx`. This is the only part of the effect a player has to be able
	// to *read*: inside it you are cargo, outside it you can still fight. An
	// effect whose visible edge is not its real one is the most confusing thing a
	// field ability can do, and the first version had the black core at 62% of the
	// radius with nothing marking the rest.
	const horizon = new Graphics();
	horizon.circle(64, 64, 60).stroke({ width: 3, color: 0xe6d2ff, alpha: 0.95 });
	horizon.circle(64, 64, 56).stroke({ width: 6, color: 0x9a5cff, alpha: 0.45 });
	horizon.circle(64, 64, 51).stroke({ width: 10, color: 0x6a2fd0, alpha: 0.2 });
	bake(renderer, TEX.horizon, horizon);

	// ---- the accretion disk ----
	//
	// An ellipse rather than a circle, because a disk seen from slightly above is
	// what makes a flat sprite read as a three-dimensional object. Two of these
	// counter-rotate at different rates in `BlackHoleFx`, which is what sells the
	// spin — one ring rotating alone reads as a rotating ring.
	const disk = new Graphics();
	for (const [r, w, colour, alpha] of [
		[60, 5, 0xffffff, 0.9],
		[68, 4, 0xffd9a0, 0.75],
		[76, 3, 0xff9a4d, 0.55],
		[84, 2, 0xb14bff, 0.4],
	] as const) {
		disk
			.ellipse(88, 88, r, r * 0.34)
			.stroke({ width: w, color: colour, alpha });
	}
	bake(renderer, TEX.accretion, disk);

	// ---- the grenade ----
	//
	// A dark core inside a corona: the same read as the hole it becomes, at a
	// twentieth the size, so a player who has seen one knows what is arriving.
	const grenade = new Graphics();
	grenade.circle(16, 16, 14).fill({ color: 0x9a5cff, alpha: 0.25 });
	grenade.circle(16, 16, 10).fill({ color: 0x6a2fd0, alpha: 0.65 });
	grenade.circle(16, 16, 6).fill(0x0a0014);
	grenade
		.circle(16, 16, 6.5)
		.stroke({ width: 1.5, color: 0xd7b3ff, alpha: 0.9 });
	bake(renderer, TEX.grenade, grenade);

	// ---- the halo ----
	//
	// A soft filled disc, white so it can be tinted. Used additively for the
	// gravitational glow and for the detonation flash — the only two things in
	// the game that need light rather than an outline.
	const halo = new Graphics();
	for (let i = 8; i >= 1; i--) {
		halo.circle(64, 64, (64 * i) / 8).fill({ color: 0xffffff, alpha: 0.055 });
	}
	bake(renderer, TEX.halo, halo);
}

/**
 * The two "you have been hit" sprites, drawn *from the dude sheet itself*.
 *
 * Every sword hit now puts its target into a disabled state, and a state nobody
 * can see is a state that does not exist: through the whole LAN playtest the
 * sword landed, the fighter kept walking, and the hit read as nothing happening.
 * These are placeholders in the honest sense — they are the shipped character,
 * flushed and knocked about, so they line up perfectly with the walk cycle and
 * are replaced by deleting this function when the real art lands.
 *
 * Both bake onto the same canvas, and it is **centred on the body's centre** —
 * `syncSpriteToBody` centres a sprite on the collider, so anything drawn off that
 * centre is drawn off the fighter. That is also why the canvas is bigger than the
 * body: a fighter lying down is 48px long inside a 32px-wide collider, and a
 * texture cropped to its own content would have been re-centred on the content
 * instead of on the fighter, leaving it hovering in the middle of the box it is
 * meant to be lying at the bottom of.
 */
function createHitTextures(renderer: Renderer): void {
	// The face-on frame. Staggering is not a direction, so the fighter turns to
	// the camera for it, exactly as the existing `turn` clip does.
	const source = dudeFrames[4] ?? dudeFrames[0];
	if (!source) return;

	/** Padding around the body, so a prone or tilted pose cannot crop the canvas. */
	const PAD = 8;
	/**
	 * An invisible rect centred on the body centre.
	 *
	 * `generateTexture` bakes a container's *bounds*, so this is what fixes them:
	 * without it the canvas would shrink-wrap whatever was drawn, and every pose
	 * would end up centred on a different point.
	 */
	const canvas = () =>
		new Graphics()
			.rect(-PAD, -PAD, PLAYER_WIDTH + PAD * 2, PLAYER_HEIGHT + PAD * 2)
			.fill({ color: 0x000000, alpha: 0 });

	// ---- staggered ----
	const stagger = new Container();
	stagger.addChild(canvas());

	const hurt = new Sprite(source);
	hurt.anchor.set(0.5, 1);
	// Rocked back off balance, and flushed red. Both read at a glance and at speed,
	// which is the only thing a placeholder has to do.
	hurt.position.set(PLAYER_WIDTH / 2, PLAYER_HEIGHT);
	hurt.rotation = -0.16;
	hurt.tint = 0xff8f8f;
	stagger.addChild(hurt);

	// Stars over the head: the one piece that is not the original sprite, because
	// "disabled" has to be distinguishable from "tinted by a filter".
	const stars = new Graphics();
	for (const [sx, sy, r] of [
		[7, 5, 3],
		[16, 2, 4],
		[25, 6, 3],
	] as const) {
		stars.poly([sx, sy - r, sx + r, sy, sx, sy + r, sx - r, sy]);
	}
	stars.fill(0xffe066);
	stagger.addChild(stars);

	bake(renderer, TEX.disabled, stagger);

	// ---- on the floor ----
	const down = new Container();
	down.addChild(canvas());

	const prone = new Sprite(source);
	prone.anchor.set(0.5, 1);
	// A quarter turn, then placed so the body lies along the bottom of the canvas:
	// rotating about the feet maps the sprite's height onto x, so the position is
	// where the *feet* end up, not where the head does.
	prone.rotation = -Math.PI / 2;
	prone.position.set(PLAYER_WIDTH + PAD, PLAYER_HEIGHT - PLAYER_WIDTH / 2);
	prone.tint = 0xd08a8a;
	down.addChild(prone);

	const dust = new Graphics();
	dust.ellipse(PLAYER_WIDTH / 2, PLAYER_HEIGHT - 1, 17, 4);
	dust.fill({ color: 0xffffff, alpha: 0.35 });
	down.addChild(dust);

	bake(renderer, TEX.downed, down);
}
