#!/usr/bin/env python3
"""Generate Lia's pixel-art sprite sheets: the nine-frame character strip, in
the Chrono Trigger / SNES style the project commits to.

The layout is fixed by the game, not by this script:

- `dude.png` — 576x96, nine 64x96 cells: 0-3 walk left, 4 face-on, 5-8 walk
  right (mirrors of 0-3). 2x art drawn at half size through `sheetScale` —
  the Anands standard: the collider stays 32x48, the pixels double, and the
  hero-select portrait, the ultimate cinematic and the move list all read
  crisp instead of blocky. (The sheet keeps its legacy `dude` filename so no
  loader changes.)
- `roll.png` — 1280x96, sixteen 80x96 cells: 0-7 roll right, 8-15 roll left
  (mirrors). Generated by `scripts/make-roll-art.py` from this strip's
  face-on frame, exactly like the hit poses in `render/assets.ts` are.

Lia is the onion-knight: a pointed purple hood, a round orange face with big
dark eyes and a toothy grin, a stubby brown-gold body. The palette is the
sheet's contract — the hit poses are derived from this sheet in code
(`createHeroPoses`), so the colours here are what the whole hero is drawn
from.

Pixel-art rules this sheet follows:

- Light from the upper left: hood, face and tunic each carry a light band on
  the left and a shade band on the right; the outline stays on the silhouette.
- A four-beat walk: contact, passing, contact, passing. Contacts plant wide
  and ride 2px low, passings pull the feet under and ride high, the near arm
  counter-swings. Frame 0 doubles as the idle.
- 2x earns its keep in the face: big rounded eyes with shines, a grin with
  separated teeth, a deep hood rim — the face-on frame is the hero-select
  portrait, so it is drawn, not doubled.

Usage: python3 scripts/make-dude-art.py && python3 scripts/make-roll-art.py
"""

from PIL import Image, ImageDraw

OUT_DIR = "public/assets"
CELL_W, CELL_H = 64, 96
GROUND_LINE = 92
STRIP_OUT = f"{OUT_DIR}/dude.png"

# ---- palette -------------------------------------------------------------
OUT = (26, 20, 44)          # silhouette outline only
HOOD = (128, 84, 200)       # purple hood base
HOOD_S = (92, 52, 160)      # hood shade, right side
HOOD_L = (168, 132, 220)    # hood light, left side
HOOD_D = (64, 32, 120)      # deep rim inside the face opening
FACE = (250, 170, 60)       # orange face base
FACE_S = (210, 125, 40)     # face shade, lower right
FACE_L = (255, 205, 120)    # face light, upper left
EYE_D = (40, 24, 40)        # big dark eyes
TEETH = (245, 245, 240)     # grin + eye shines
MOUTH = (120, 50, 30)       # mouth dark
GOLD = (230, 190, 90)       # front panel, buckle, toe caps
TUNIC = (150, 100, 55)      # brown tunic
TUNIC_S = (110, 68, 38)     # tunic shade
BELT = (60, 40, 40)         # dark belt
BOOT = (74, 52, 66)         # boots
BOOT_S = (50, 34, 46)       # boot shade
SOLE = (30, 20, 26)         # sole line

CHARS = {
    ".": None,
    "O": OUT,
    "H": HOOD,
    "h": HOOD_S,
    "K": HOOD_L,
    "k": HOOD_D,
    "F": FACE,
    "f": FACE_S,
    "l": FACE_L,
    "E": EYE_D,
    "W": TEETH,
    "M": MOUTH,
    "D": GOLD,
    "T": TUNIC,
    "t": TUNIC_S,
    "B": BELT,
    "V": BOOT,
    "v": BOOT_S,
    "Z": SOLE,
}


def paint(rows: list[str], ox: int = 0, oy: int = 0) -> Image.Image:
    """Paint row-string maps at 1:1 onto a fresh 64x96 cell.

    Every row must be exactly 64 chars: a short row used to silently right-pad
    and shift nothing, but it hid typos for a year, so now it fails loudly.
    """
    img = Image.new("RGBA", (CELL_W, CELL_H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    for y, row in enumerate(rows):
        if len(row) != CELL_W:
            raise ValueError(f"row {y} is {len(row)} chars, expected {CELL_W}: {row!r}")
        for x, ch in enumerate(row):
            colour = CHARS.get(ch)
            if colour is None:
                continue
            draw.point([(ox + x, oy + y)], fill=colour + (255,))
    return img


def layer(base: Image.Image, rows: list[str], oy: int = 0) -> Image.Image:
    """Paint row-strings over an existing cell (limbs over the torso)."""
    draw = ImageDraw.Draw(base)
    for y, row in enumerate(rows):
        if len(row) != CELL_W:
            raise ValueError(f"row {y} is {len(row)} chars, expected {CELL_W}: {row!r}")
        for x, ch in enumerate(row):
            colour = CHARS.get(ch)
            if colour is None:
                continue
            draw.point([(x, oy + y)], fill=colour + (255,))
    return base


FACE = [
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "...............................OO...............................",
    ".............................OHHHHO.............................",
    "...........................KHHHHHHHHO...........................",
    ".........................OHHHHHHHHHHHHO.........................",
    ".......................OHHHHKHHHHHHHHHHHO.......................",
    ".....................OHHHHHHHHHHHHHHHHHHHHO.....................",
    "....................OHHHHHHHHKHHHHHHHHHHHHHO....................",
    "...................OHHHHHHHHHHHHHHHHHHHHHHHHO...................",
    "..............KKK.OHHHHHHHHHHHHHHHHHHHHHHHHHHO.hhh..............",
    "..................OHHHHHHHHHHHHHHHHHHHHHHHHHHO..................",
    "..............KKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhh..............",
    "................OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO................",
    "..............KKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhh..............",
    "...............OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO...............",
    "..............KKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhh..............",
    "..............OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO..............",
    ".............OKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhO.............",
    ".............OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO.............",
    "............OHKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhHO............",
    "............OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO............",
    "............OHKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhHO............",
    "............OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO............",
    "...........OHHKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhHHO...........",
    "...........OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO...........",
    "...........OHHKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhHHO...........",
    "...........OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO...........",
    "...........OHHKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhHHO...........",
    "...........OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHO...........",
    "...........OHHKKKkOOOOO..................OOOOOkhhhHHO...........",
    "...........OHHkkkOOOOOO..................OOOOOOkkkHHO...........",
    "...........OHHKKKOllllFFFFF..........FFFFFllllOhhhHHO...........",
    "...........OHHkkOlllFFFFFFFFF......FFFFFFFFFlllOkkHHO...........",
    "...........OHHKKKllFFFllFFFFFFF..FFFFFFFFFFFFllhhhHHO...........",
    "...........OHHkOllFFFFlFFFFFFFF..FFFFFFFFFFFFFllOkHHO...........",
    "...........OHHKKKlFFWWEEEEFFFFF..FFFFFEEEEWWFFlhhhHHO...........",
    "...........OHHkOllFFWWEEEEFFFFF..FFFFFEEEEWWFFllOkHHO...........",
    "...........OHHKKKlFFFEEEEEEFFFF..FFFFEEEEEEFFFlhhhHHO...........",
    "...........OHHkOllFFFEEEEEEFFFF..FFFFEEEEEEFFFllOkHHO...........",
    "...........OHHKKKlFFFEEEEEEFFFF..FFFFEEEEEEFFFlhhhHHO...........",
    "...........OHHkOllFFFEEEEEEFFFF..FFFFEEEEEEFFFllOkHHO...........",
    "...........OHHKKKlFFFFEEEEFFFFF..FFFFFEEEEFFFFlhhhHHO...........",
    "...........OHHkOllFFFFFFEEEEFFF..FFFEEEEFFFFFFllOkHHO...........",
    "...........OHHKKKlFFFFFFFFFFFFFFFFFFFFFFFFFFFFlhhhHHO...........",
    "...........OHHkOllFFMMMMMMMMMMFFFFMMMMMMMMMMFFllOkHHO...........",
    "...........OHHKKKlFFWWWMWWMWWWFFFFWWWMWWffWWFFlhhhHHO...........",
    "...........OHHkOllFFWWWMWWMWWWFFFFWWWMWWffWWFFllOkHHO...........",
    "...........OHHKKKlFFFFMMMMMMFFFFFFFFMMMMfMFFFFlhhhHHO...........",
    "...........OHHkkOOffffffffffffO..OffffffffffffOOkkHHO...........",
    "...........OHHHkkkOOOOO..................OOOOOkkkHHHO...........",
    "...........OHHHHHkkkkOOOO..............OOOOkkkkHHHHHO...........",
    "............OHHHHHHHHkkkOOO..........OOOkkkHHHHHHHHO............",
    ".............OHHHHHHHHHHkkOO........OOkkHHHHHHHHHHO.............",
    "..............OHHHHHHHHhhhhO........OhhhhHHHHHHHHO..............",
    "................OHHHHhhhhO............OhhhhHHHHO................",
    "................OHHHHhhhhO............OhhhhHHHHO................",
    "................OHHHHhhhhO............OhhhhHHHHO................",
]

TORSO = [
    "....................OOOOOOOOOOOOOOOOOOOOOOOO....................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "...................OTTTTTTTTTTTTTTTTTTTTTTTTO...................",
    "...................OTTTTDDDDDDDDDDDDDDDDTTTTO...................",
    "...................OTTTDDDDDDDDDDDDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OtttDDDDDDDttttDDDDDDDtttO...................",
    "...................OBBBBBBBBBBBBBBBBBBBBBBBBO...................",
    "...................OBBBBBBBBDDDDDDDDBBBBBBBBO...................",
    "...................OBBBBBBBBWDDDDDDWBBBBBBBBO...................",
    "...................OBBBBBBBBBBBBBBBBBBBBBBBBO...................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "....................OOOOOOOOOOOOOOOOOOOOOOOO....................",
]

LEGS = [
    [
        "......................OOOO......OOOO............................",
        "......................OTTO......OTTO............................",
        "......................OTTO......OTTO............................",
        "......................OTTO......OTTO............................",
        "......................OTTO......OTTO............................",
        ".....................OVVVO......OVVVO...........................",
        ".....................OVDDVO.....OVDDVO..........................",
        ".....................OZZZZO.....OZZZZO..........................",
    ],
    [
        "................................................................",
        "........................OOOO....OOOO............................",
        "........................OTTO....OTTO............................",
        "........................OTTO....OTTO............................",
        "........................OTTO....OVVO............................",
        "........................OVVO....OVDVO...........................",
        "........................OVDVO....OZZO...........................",
        "........................OZZZO...................................",
    ],
    [
        "......................OOOO......OOOO............................",
        "......................OTTO......OTTO............................",
        "......................OTTO......OTTO............................",
        "......................OTTO......OTTO............................",
        "......................OTTO......OTTO............................",
        ".....................OVVVO......OVVVO...........................",
        ".....................OVDDVO.....OVDDVO..........................",
        ".....................OZZZZO.....OZZZZO..........................",
    ],
    [
        "................................................................",
        "........................OOOO....OOOO............................",
        "........................OTTO....OTTO............................",
        "........................OTTO....OTTO............................",
        "........................OVVO....OTTO............................",
        "........................OVDVO...OVVO............................",
        ".........................OZZO...OVDVO...........................",
        "................................OZZZO...........................",
    ],
]

ARMS = [
    [
        "..............OTTTTTT......................TTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "................................................................",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "...............FFFFF........................FFFFF...............",
        "................FFF..........................FFF................",
        "................................................................",
        "................................................................",
    ],
    [
        "..............OTTTTTT......................TTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "...............FFFFF........................FFFFF...............",
        "................FFF..........................FFF................",
        "................................................................",
        "................................................................",
        "................................................................",
        "................................................................",
    ],
    [
        "..............OTTTTTT......................TTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "................................................................",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "...............FFFFF........................FFFFF...............",
        "................FFF..........................FFF................",
        "................................................................",
        "................................................................",
    ],
    [
        "..............OTTTTTT......................TTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OTTTTTt......................tTTTTTO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "..............OFFFFFF......................FFFFFFO..............",
        "...............FFFFF........................FFFFF...............",
        "................FFF..........................FFF................",
        "................................................................",
        "................................................................",
        "................................................................",
        "................................................................",
    ],
]

PHEAD = [
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "................................................................",
    "...............................OO...............................",
    ".............................OHHHHO.............................",
    "...........................OHHHHHHO.............................",
    ".........................OHHHHHHHHO.............................",
    "........................OHHHHHHHHHHO............................",
    "......................OHHHHHHHHHHHHO............................",
    ".....................OHHHHHHHHHHHHHO............................",
    "....................OHHHHHHHHHHHHHHO............................",
    "...................OHHHHHHHHHHHHHHHO............................",
    "...................OHHHHHHHHHHHHHHHO............................",
    ".................OHHHHHHHHHHHHHHHHHO............................",
    ".................OHHHHHHHHHHHHHHHHHO............................",
    "................OHHHHHHHHHHHHHHHHHH.O...........................",
    "................OHHHHHHHHHHHHHHHHHH.O...........................",
    "...............OKHHHHHHHHHHHHHHHHHH..O..........................",
    "...............OHHHHHHHHHHHHHHHHHHH..O..........................",
    "..............OKKHHHHHHHHHHHHHHHHHH...O.........................",
    "..............OHHHHHHHHHHHHHHHHHHHH...O.........................",
    ".............OKKKHHHHHHHHHHHHHHHHHH....O........................",
    ".............OHHHHHHHHHHHHHHHHHHHHH....O........................",
    ".............OKKKHHHHHHHHHHHHHHHHHH....O........................",
    ".............OHHHHHHHHHHHHHHHHHHHHH....O........................",
    "............OHKKKHHHHHHHHHHHHHHHHHHHHHHHO.......................",
    "............OHHHHHHHHHHHHHHHHHHHHHHHHHHHO.......................",
    "............OHKKKHHHHHHHHHHHHHHHHHHHHHHHO.......................",
    "............OHHHHHHHHHHHHHHHHHHHHHHHHHHHO.......................",
    "............OHKKKHHHHHHHHHHHHHHHHHHHHHHHO.......................",
    "............OHHHHHHHHHHHHHHHHHHHHHHHHHHHO.......................",
    "............OHKkkkOOOOOOOHHHHHHHHHHHHHHHHO......................",
    "............OHHkkOOOOOOOOHHHHHHHHHHHHHHHHO......................",
    "............OHKkOlllllFFFFFFFFHHHHHHHHHHHO......................",
    "............OHHkOlllFFFFFFFFFHHHHHHHHHHHHO......................",
    "............OHKkOllFFFFFFFFFHHHHHHHHHHHHHO......................",
    "............OHHkOllFFFFFFFFFHHHHHHHHHHHHHHO.....................",
    "............OHKkOllFFWWEEEEFFFHHHHHHHHHHHHO.....................",
    "............OHHkOllFFWWEEEEFFFHHHHHHHHHHHHO.....................",
    "............OHKkOllFFFEEEEEEFFFHHHHHHHHHHHO.....................",
    "..........OFFHHkOllFFFEEEEEEFFFHHHHHHHHHHHO.....................",
    "........OFFFFHKkOllFFFEEEEEEFFFHHHHHHHHHHHO.....................",
    "........OFFFFHHkOllFFFEEEEEEFFFHHHHHHHHHHHO.....................",
    "........OFFFFHKkOllFFFFEEEEFFFHHHHHHHHHHHHO.....................",
    "..........OFFFFkOllFFFFFFEEEEFFHHHHHHHHHHHO.....................",
    "............OHKkOllFFFFFFFFFFFFHHHHHHHHHHHO.....................",
    "............OHHkOllFFMMMMMMMMFFHHHHHHHHHHHO.....................",
    "............OHKkOllFFWWWWMWWWWFHHHHHHHHHHHO.....................",
    "............OHHkOllFFWWWWMWWWWFHHHHHHHHHHHO.....................",
    "............OHKkOllFFFFMMMMMFFFHHHHHHHHHHHO.....................",
    "............OHHkkOfffffffffO....................................",
    "............OHKKKHHHHHHHHHHHHHHHHHHHHHO.........................",
    "............OHHHHHHHHHHHHHHHHHHHHHHHO...........................",
    ".............OHHHHHHHHHHHHHHHHHHHHO.............................",
    "..............OHHHHHHHHHHHHHHHHHO...............................",
    "................OHHHHHHHHHHHHHO.................................",
    "..................OHHHHHHHHHO...................................",
    "................................................................",
    "................................................................",
]

PTORSO = [
    "....................OOOOOOOOOOOOOOOOOOOOOOOO....................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "...................OTTTTTTTTTTTTTTTTTTTTTTTTO...................",
    "...................OTTTTDDDDDDDDDDDDDDDDTTTTO...................",
    "...................OTTTDDDDDDDDDDDDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OTTTDDDDDDDttttDDDDDDDTTTO...................",
    "...................OtttDDDDDDDttttDDDDDDDtttO...................",
    "...................OBBBBBBBBBBBBBBBBBBBBBBBBO...................",
    "...................OBBBBBBBBDDDDDDDDBBBBBBBBO...................",
    "...................OBBBBBBBBWDDDDDDWBBBBBBBBO...................",
    "...................OBBBBBBBBBBBBBBBBBBBBBBBBO...................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "....................OTTTTTTTTTTTTTTTTTTTTTTO....................",
    "....................OOOOOOOOOOOOOOOOOOOOOOOO....................",
]

PLEGS = [
    [
        "................OOOO................OOOO........................",
        "..............OOTTTTOO..............OOTTOO......................",
        "..............OOTTTTOO..............OOTTOO......................",
        "..............OOTTTTOO..............OOTTOO......................",
        "..............OOTTTTOO..............OOTTOO......................",
        ".............OOVVVVVOO...............OVVOO......................",
        ".............OOVDDVVOO...............OVDOO......................",
        ".............OOZZZZZOO...............OZZOO......................",
    ],
    [
        "........................OOOO....................................",
        "......................OOTTTTOO......OOOOOO......................",
        "......................OOTTTTOO......OOTTOO......................",
        "......................OOTTTTOO......OOTTOO......................",
        "......................OOVVVVOO.......OOTTOO.....................",
        "......................OOVDDVVOO......OOVVOO.....................",
        "......................OOZZZZVOO......OOVDOO.....................",
        "......................OOZZZZVOO.......OZZOO.....................",
    ],
    [
        "................OOOO................OOOO........................",
        "................OOTTOO..............OOTTTTOO....................",
        "................OOTTOO..............OOTTTTOO....................",
        "................OOTTOO..............OOTTTTOO....................",
        "................OOTTOO..............OOTTTTOO....................",
        ".................OVVOO...............OOVVVVVOO..................",
        ".................OVDOO...............OOVDDVVOO..................",
        ".................OZZOO...............OOZZZZZOO..................",
    ],
    [
        "................................OOOO............................",
        "..................OOOOOO......OOTTTTOO..........................",
        "..................OOTTOO......OOTTTTOO..........................",
        "..................OOTTOO......OOTTTTOO..........................",
        "...................OOTTOO......OOVVVVOO.........................",
        "...................OOVVOO......OOVDDVVOO........................",
        "...................OOVDOO......OOZZZZVOO........................",
        "....................OZZOO.......OOZZZZVOO.......................",
    ],
]

PARMS = [
    [
        "............................TTTTTT..............................",
        "............................TTTTTTT.............................",
        ".............................TTTTTTT............................",
        ".............................TTTTTTTT...........................",
        "..............................TTTTTTTT..........................",
        "..............................TTTTTTTT..........................",
        "..............................TTTTTTTT..........................",
        "..............................TTTTTTTT..........................",
        "..............................TTTTTTTT..........................",
        "..............................TTTTTTTT..........................",
        "..............................TTTTTTTT..........................",
        "..............................TTTTTTTT..........................",
        "..............................FFFFFFOO..........................",
        "..............................FFFFFFOO..........................",
        "..............................FFFFFFOO..........................",
        "...............................FFFFFO...........................",
        "...............................FFFFFO...........................",
        "................................................................",
        "................................................................",
        "................................................................",
    ],
    [
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................FFFFFF................................",
        "..........................FFFFFF................................",
        "..........................FFFFFF................................",
        "...........................FFFF.................................",
        "...........................FFFF.................................",
        "................................................................",
        "................................................................",
        "................................................................",
    ],
    [
        "........................TTTTTT..................................",
        "......................TTTTTTTT..................................",
        ".....................TTTTTTTT...................................",
        "....................TTTTTTTT....................................",
        "...................TTTTTTTT.....................................",
        "...................TTTTTTTT.....................................",
        "...................TTTTTTTT.....................................",
        "...................TTTTTTTT.....................................",
        "...................TTTTTTTT.....................................",
        "...................TTTTTTTT.....................................",
        "...................TTTTTTTT.....................................",
        "...................TTTTTTTT.....................................",
        "..................OOFFFFFF......................................",
        "..................OOFFFFFF......................................",
        "..................OOFFFFFF......................................",
        "...................FFFFFF.......................................",
        "...................FFFFFF.......................................",
        "................................................................",
        "................................................................",
        "................................................................",
    ],
    [
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................TTTTTT................................",
        "..........................FFFFFF................................",
        "..........................FFFFFF................................",
        "..........................FFFFFF................................",
        "...........................FFFF.................................",
        "...........................FFFF.................................",
        "................................................................",
        "................................................................",
        "................................................................",
    ],
]


def face_frame() -> Image.Image:
    img = paint(FACE, 0, 0)
    layer(img, TORSO, 62)
    layer(img, LEGS[0], 85)
    layer(img, ARMS[1], 62)
    return img


def front_walk_frame(i: int) -> Image.Image:
    bob = -2 if i in (1, 3) else 0
    img = paint(FACE, 0, bob)
    layer(img, TORSO, 62 + bob)
    layer(img, LEGS[i], 85)
    layer(img, ARMS[i], 62)
    return img


def profile_frame(leg_idx: int) -> Image.Image:
    bob = -2 if leg_idx in (1, 3) else 0
    img = paint(PHEAD, 0, bob)
    layer(img, PTORSO, 62 + bob)
    layer(img, PLEGS[leg_idx], 85)
    layer(img, PARMS[leg_idx], 62 + bob)
    return img


def build_strip() -> None:
    img = Image.new("RGBA", (CELL_W * 9, CELL_H), (0, 0, 0, 0))
    left = [profile_frame(i) for i in range(4)]
    face = face_frame()
    for i, f in enumerate(left):
        img.paste(f, (i * CELL_W, 0))
    img.paste(face, (4 * CELL_W, 0))
    for i, f in enumerate(left):
        img.paste(f.transpose(Image.FLIP_LEFT_RIGHT), ((5 + i) * CELL_W, 0))
    img.save(STRIP_OUT)
    print(f"wrote {STRIP_OUT} ({img.width}x{img.height})")


if __name__ == "__main__":
    build_strip()
